from __future__ import annotations


CANDIDATE_REPORT_CONTRACT = (
    "CURRENT_REVISED_COMPANY_SNAPSHOT_V2_PRESENTATION_V8_RELATIVE_VALUATION_CANDIDATE"
)

PRODUCTION_REPORT_CONTRACT = (
    "CURRENT_REVISED_COMPANY_SNAPSHOT_V2_PRESENTATION_V8_RELATIVE_VALUATION"
)
